In [2]:
import pandas as pd
import numpy as np
import pandas_datareader as pdr
from bs4 import BeautifulSoup
import requests
from pandas_datareader import data as pdr
import yfinance as yf
yf.pdr_override()

In [ ]:
resp = requests.get("https://stockmarketmba.com/stocksinthesp500.php")
soup = BeautifulSoup(resp.text, 'lxml')
table = soup.find('table', {'id': 'ipos'})
rows = table.find('tbody').find_all('tr')

tickers = []
industries = []

for row in rows:
    ticker = row.find_all('td')[0].text.strip()
    tickers.append(ticker)
    industry = row.find_all('td')[4].text.strip()
    industries.append(industry)

df_list = []
no_data = []

for i in range(len(tickers)):
    try:
        temp = pdr.get_data_yahoo(tickers[i], start='2003-06-01', end='2022-10-31')
        temp['symbol'] = tickers[i]
        temp['industry'] = industries[i]
        df_list.append(temp)
    except:
        no_data.append(tickers[i])

main_df = pd.concat(df_list)
main_df.to_csv("SP500 stock OHLC extended.csv")
print(main_df)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [14]:
main_df['industry'] = np.where(main_df.industry=='Information technology', 'Information Technology', main_df.industry)
main_df.industry.unique()

array(['Health Care', 'Industrials', 'Consumer Discretionary',
       'Information Technology', 'Financials', 'Consumer Staples',
       'Utilities', 'Materials', 'Real Estate', 'Energy',
       'Communication Services'], dtype=object)

In [15]:
initial_ticker = main_df.loc[main_df.index == main_df.index.unique()[0]].symbol.unique()
last_month_df = main_df.loc[main_df.index == main_df.index.unique()[-1]]
survived_tickers = last_month_df.loc[last_month_df.symbol.isin(initial_ticker)].symbol.unique()
len(survived_tickers)

393

In [16]:
main_df = main_df.loc[main_df.symbol.isin(survived_tickers)]
main_df

,Open,High,Low,Close,Adj Close,Volume,symbol,industry
Date,,,,,,,,
2003-06-02,13.590844,13.683834,13.268956,13.397711,11.463510,6300926.0,A,Health Care
2003-06-03,13.397711,13.648069,13.319027,13.626609,11.659362,4041758.0,A,Health Care
2003-06-04,13.590844,14.270386,13.583691,14.241774,12.185717,2874568.0,A,Health Care
2003-06-05,14.127325,14.163090,13.762518,14.055794,12.026588,4139758.0,A,Health Care
2003-06-06,14.127325,14.234621,13.733906,13.812589,11.818497,4395452.0,A,Health Care
...,...,...,...,...,...,...,...,...
2022-10-24,48.320000,50.049999,48.130001,49.779999,49.377518,2713000.0,ZION,Financials
2022-10-25,47.720001,51.869999,47.490002,51.509998,51.093529,3797100.0,ZION,Financials
2022-10-26,51.040001,51.939999,50.349998,50.400002,49.992508,1623000.0,ZION,Financials
2022-10-27,51.060001,51.520000,50.189999,50.380001,49.972668,1134600.0,ZION,Financials
2022-10-28,50.779999,51.610001,50.430000,51.540001,51.123291,1196000.0,ZION,Financials

In [17]:
main_df.to_csv("SP500 stock OHLC extended.csv")